version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: 'rebeca'
      POSTGRES_USER: 'rebeca'
      POSTGRES_PASSWORD: 'rebequinha2020'
  web:
    build: .
    command: gunicorn rebeca.wsgi --bind 0.0.0.0:8000 
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

