# Generated by Django 3.0.5 on 2020-04-24 16:30

from django.db import migrations, models
import django.db.models.deletion
import records.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da cidade')),
                ('federal_unit', models.CharField(choices=[('AC', 'Acre (AC)'), ('AL', 'Alagoas (AL)'), ('AP', 'Amapá (AP)'), ('AM', 'Amazonas (AM)'), ('BA', 'Bahia (BA)'), ('CE', 'Ceará (CE)'), ('DF', 'Distrito Federal (DF)'), ('ES', 'Espírito Santo (ES)'), ('GO', 'Goiás (GO)'), ('MA', 'Maranhão (MA)'), ('MT', 'Mato Grosso (MT)'), ('MS', 'Mato Grosso do Sul (MS)'), ('MG', 'Minas Gerais (MG)'), ('PA', 'Pará (PA)'), ('PB', 'Paraíba (PB)'), ('PR', 'Paraná (PR)'), ('PE', 'Pernambuco (PE)'), ('PI', 'Piauí (PI)'), ('RJ', 'Rio de Janeiro (RJ)'), ('RN', 'Rio Grande do Norte (RN)'), ('RS', 'Rio Grande do Sul (RS)'), ('RO', 'Rondônia (RO)'), ('RR', 'Roraima (RR)'), ('SC', 'Santa Catarina (SC)'), ('SP', 'São Paulo (SP)'), ('SE', 'Sergipe (SE)'), ('TO', 'Tocantins (TO)')], max_length=2, verbose_name='UF')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Gênero',
                'verbose_name_plural': 'Gêneros',
            },
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do bairro')),
            ],
            options={
                'verbose_name': 'Bairro',
                'verbose_name_plural': 'Bairros',
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Raça',
                'verbose_name_plural': 'Raças',
            },
        ),
        migrations.CreateModel(
            name='Scolarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Escolaridade',
                'verbose_name_plural': 'Escolaridades',
            },
        ),
        migrations.CreateModel(
            name='SocialBenefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Benefício social',
                'verbose_name_plural': 'Benefícios sociais',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome usuárix')),
                ('date_of_birth', models.DateField(verbose_name='Data de nascimento')),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[records.utils.validate_cpf], verbose_name='CPF ')),
                ('debts', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='Dídivas')),
                ('agreement', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='Possui convênio')),
                ('family_composition', models.IntegerField(verbose_name='Composição familiar')),
                ('estimated_income', models.CharField(choices=[('Até um salário mínimo', 'Até um salário mínimo'), ('De um a dois salários mínimos', 'De um a dois salários mínimos'), ('De dois a três salários mínimos', 'De dois a três salários mínimos'), ('Mais de três salários mínimos', 'Mais de três salários mínimos')], max_length=32, verbose_name='Renda estimada')),
                ('source_of_income', models.CharField(choices=[('Informal apenas', 'Informal apenas'), ('Formal apenas', 'Formal apenas'), ('Ambas', 'Ambas')], max_length=30, verbose_name='Fonte da renda')),
                ('housing_condition', models.CharField(choices=[('Própria', 'Pŕopria'), ('Alugada', 'Alugada'), ('Cedida', 'Cedida'), ('Financiada', 'Financiada')], max_length=30, verbose_name='Condição de moradia')),
                ('treatment', models.CharField(choices=[('Até um ano', 'Até um ano'), ('Um a dois anos', 'Um a dois anos'), ('Dois a três anos', 'Dois a três anos'), ('Mais de três anos', 'Mais de três anos')], max_length=30, verbose_name='Tempo de tratamento')),
                ('medication_origin', models.CharField(choices=[('Farmácia municipal', 'Farmácia municipal'), ('Compra', 'Compra'), ('Farmácia municipal e compra', 'Farmácia municipal e compra'), ('Outros', 'Outros')], max_length=30, verbose_name='Origem da medicação')),
                ('health_problems_in_family', models.CharField(choices=[('Não', 'Não'), ('Sim, são tratados', 'Sim, são tratados'), ('Sim, não são tratados', 'Sim, não são tratados')], max_length=30, verbose_name='Doenças na família')),
                ('old_people_in_family', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='Idosos na família')),
                ('disabled_in_family', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='Deficientes na família')),
                ('early_pregnancy', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='Gravidez precoce')),
                ('pregnant_or_lactating', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='Gestante ou lactante')),
                ('alcohol_or_drug_user', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='Usuário de álcool ou drogas')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Genre', verbose_name='Gênero')),
                ('natural_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.City', verbose_name='Naturalidade')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Neighborhood', verbose_name='Bairro')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Race', verbose_name='Raça')),
                ('scholarity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Scolarity', verbose_name='Escolaridade')),
                ('social_benefits', models.ManyToManyField(blank=True, to='records.SocialBenefit', verbose_name='Benefícios sociais')),
            ],
            options={
                'verbose_name': 'Questionário',
                'verbose_name_plural': 'Questionários',
            },
        ),
    ]
