# Generated by Django 2.1.5 on 2019-01-26 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da cidade')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da doença')),
            ],
            options={
                'verbose_name': 'Doença',
                'verbose_name_plural': 'Doenças',
            },
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do bairro')),
            ],
            options={
                'verbose_name': 'Bairro',
                'verbose_name_plural': 'Bairros',
            },
        ),
        migrations.CreateModel(
            name='PersonWithDisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('kinship', models.CharField(choices=[('1', 'Pai'), ('2', 'Mãe'), ('3', 'Irmão / irmã'), ('4', 'Filhx'), ('5', 'Outros')], max_length=1, verbose_name='Parentesco')),
                ('treatment', models.CharField(choices=[('y', 'Sim'), ('n', 'Não')], max_length=1, verbose_name='Faz tratamento')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.Disease', verbose_name='Doença')),
            ],
            options={
                'verbose_name': 'Pessoa com doença na família',
                'verbose_name_plural': 'Pessoas com doenças nas famílias',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da pessoa usuária')),
                ('date_of_birth', models.DateField(verbose_name='Data de nascimento')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF ')),
                ('scholarity', models.CharField(choices=[('1', 'Ensino fundamental incompleto'), ('2', 'Ensino fundamental completo'), ('3', 'Ensino médio incompleto'), ('4', 'Ensino médio completo'), ('5', 'Ensino superior incompleto'), ('6', 'Ensino superior completo')], max_length=1, verbose_name='Escolaridade')),
                ('debts', models.CharField(choices=[('y', 'Sim'), ('n', 'Não')], max_length=1, verbose_name='Dídivas')),
                ('agreement', models.CharField(choices=[('y', 'Sim'), ('n', 'Não')], max_length=1, verbose_name='Convênio')),
                ('family_composition', models.IntegerField(verbose_name='Composição familiar')),
                ('estimated_income', models.CharField(choices=[('1', 'Até um salário mínimo'), ('2', 'De um a dois salários mínimos'), ('3', 'De dois a três salários mínimos'), ('4', 'Mais de três salários mínimos')], max_length=32, verbose_name='Renda estimada')),
                ('source_of_income', models.CharField(choices=[('1', 'Informal apenas'), ('2', 'Formal apenas'), ('3', 'Ambas')], max_length=32, verbose_name='Fonte da renda')),
                ('housing_condition', models.CharField(choices=[('1', 'Pŕopria'), ('2', 'Alugada'), ('3', 'Cedida'), ('4', 'Financiada')], max_length=32, verbose_name='Condição de moradia')),
                ('treatment', models.CharField(choices=[('1', 'Até um ano'), ('2', 'Um a dois anos'), ('3', 'Dois a três anos'), ('4', 'Mais de três anos')], max_length=32, verbose_name='Tempo de tratamento')),
                ('medication_origin', models.CharField(choices=[('1', 'Farmácia municipal'), ('2', 'Compra'), ('3', 'Outros')], max_length=32, verbose_name='Origem da medicação')),
                ('old_people_in_family', models.CharField(choices=[('y', 'Sim'), ('n', 'Não')], max_length=1, verbose_name='Idosos na família')),
                ('disabled_in_family', models.CharField(choices=[('y', 'Sim'), ('n', 'Não')], max_length=1, verbose_name='Deficientes na família')),
                ('diseases_in_family', models.ManyToManyField(blank=True, to='files.PersonWithDisease', verbose_name='Pessoas com doenças na família')),
                ('natural_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.City', verbose_name='Naturalidade')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.Neighborhood', verbose_name='Bairro')),
            ],
            options={
                'verbose_name': 'Questionário',
                'verbose_name_plural': 'Questionários',
            },
        ),
        migrations.CreateModel(
            name='SocialBenefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do benefício')),
            ],
            options={
                'verbose_name': 'Benefício social',
                'verbose_name_plural': 'Benefícios sociais',
            },
        ),
        migrations.AddField(
            model_name='record',
            name='social_benefit',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='files.SocialBenefit', verbose_name='Benefício social'),
        ),
    ]
