# Generated by Django 2.2.7 on 2019-11-28 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do bairro')),
            ],
            options={
                'verbose_name': 'Bairro',
                'verbose_name_plural': 'Bairros',
            },
        ),
        migrations.CreateModel(
            name='SocialBenefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Benefício social',
                'verbose_name_plural': 'Benefícios sociais',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da pessoa usuária')),
                ('date_of_birth', models.DateField(verbose_name='Data de nascimento')),
                ('age', models.IntegerField(help_text='Idade na coleta dos dados:', verbose_name='Idade')),
                ('natural_from', models.CharField(max_length=100, verbose_name='Naturalidade')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF ')),
                ('gender', models.CharField(default='Não declarado', max_length=20, verbose_name='Gênero')),
                ('race', models.CharField(default='Não declarada', max_length=20, verbose_name='Cor ou raça')),
                ('scholarity', models.CharField(max_length=30, verbose_name='Escolaridade')),
                ('debts', models.CharField(max_length=3, verbose_name='Dídivas')),
                ('agreement', models.CharField(max_length=3, verbose_name='Possui convênio')),
                ('family_composition', models.IntegerField(verbose_name='Composição familiar')),
                ('estimated_income', models.CharField(max_length=32, verbose_name='Renda estimada')),
                ('source_of_income', models.CharField(max_length=30, verbose_name='Fonte da renda')),
                ('has_benefits', models.CharField(max_length=3, verbose_name='Possui benefício')),
                ('housing_condition', models.CharField(max_length=30, verbose_name='Condição de moradia')),
                ('treatment', models.CharField(max_length=30, verbose_name='Tempo de tratamento')),
                ('medication_origin', models.CharField(max_length=30, verbose_name='Origem da medicação')),
                ('health_problems_in_family', models.CharField(max_length=30, verbose_name='Doenças na família')),
                ('old_people_in_family', models.CharField(max_length=3, verbose_name='Idosos na família')),
                ('disabled_in_family', models.CharField(max_length=3, verbose_name='Deficientes na família')),
                ('early_pregnancy', models.CharField(max_length=3, verbose_name='Gravidez precoce')),
                ('pregnant_or_lactating', models.CharField(max_length=3, verbose_name='Gestante ou lactante')),
                ('alcohol_or_drug_user', models.CharField(max_length=3, verbose_name='Usuário de álcool ou drogas')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_cards.Neighborhood', verbose_name='Bairro')),
                ('social_benefits', models.ManyToManyField(blank=True, to='social_cards.SocialBenefit', verbose_name='Benefícios sociais')),
            ],
            options={
                'verbose_name': 'Questionário',
                'verbose_name_plural': 'Questionários',
            },
        ),
    ]
