# Generated by Django 2.2.7 on 2019-11-28 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da cidade')),
                ('federal_unit', models.CharField(choices=[('AC', 'Acre (AC)'), ('AL', 'Alagoas (AL)'), ('AP', 'Amapá (AP)'), ('AM', 'Amazonas (AM)'), ('BA', 'Bahia (BA)'), ('CE', 'Ceará (CE)'), ('DF', 'Distrito Federal (DF)'), ('ES', 'Espírito Santo (ES)'), ('GO', 'Goiás (GO)'), ('MA', 'Maranhão (MA)'), ('MT', 'Mato Grosso (MT)'), ('MS', 'Mato Grosso do Sul (MS)'), ('MG', 'Minas Gerais (MG)'), ('PA', 'Pará (PA)'), ('PB', 'Paraíba (PB)'), ('PR', 'Paraná (PR)'), ('PE', 'Pernambuco (PE)'), ('PI', 'Piauí (PI)'), ('RJ', 'Rio de Janeiro (RJ)'), ('RN', 'Rio Grande do Norte (RN)'), ('RS', 'Rio Grande do Sul (RS)'), ('RO', 'Rondônia (RO)'), ('RR', 'Roraima (RR)'), ('SC', 'Santa Catarina (SC)'), ('SP', 'São Paulo (SP)'), ('SE', 'Sergipe (SE)'), ('TO', 'Tocantins (TO)')], max_length=2, verbose_name='UF')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
            },
        ),
        migrations.AlterField(
            model_name='record',
            name='agreement',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='Possui convênio'),
        ),
        migrations.AlterField(
            model_name='record',
            name='alcohol_or_drug_user',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='Usuário de álcool ou drogas'),
        ),
        migrations.AlterField(
            model_name='record',
            name='debts',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='Dídivas'),
        ),
        migrations.AlterField(
            model_name='record',
            name='disabled_in_family',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='Deficientes na família'),
        ),
        migrations.AlterField(
            model_name='record',
            name='early_pregnancy',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='Gravidez precoce'),
        ),
        migrations.AlterField(
            model_name='record',
            name='estimated_income',
            field=models.CharField(choices=[('Até um salário mínimo', 'Até um salário mínimo'), ('De um a dois salários mínimos', 'De um a dois salários mínimos'), ('De dois a três salários mínimos', 'De dois a três salários mínimos'), ('Mais de três salários mínimos', 'Mais de três salários mínimos')], max_length=32, verbose_name='Renda estimada'),
        ),
        migrations.AlterField(
            model_name='record',
            name='gender',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Transgênero', 'Transgênero'), ('Não binário', 'Não binário'), ('Outros', 'Outros')], default='Não declarado', max_length=20, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='record',
            name='has_benefits',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='Possui benefício'),
        ),
        migrations.AlterField(
            model_name='record',
            name='health_problems_in_family',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim, são tratados', 'Sim, são tratados'), ('Sim, não são tratados', 'Sim, não são tratados')], max_length=30, verbose_name='Doenças na família'),
        ),
        migrations.AlterField(
            model_name='record',
            name='housing_condition',
            field=models.CharField(choices=[('Própria', 'Pŕopria'), ('Alugada', 'Alugada'), ('Cedida', 'Cedida'), ('Financiada', 'Financiada')], max_length=30, verbose_name='Condição de moradia'),
        ),
        migrations.AlterField(
            model_name='record',
            name='medication_origin',
            field=models.CharField(choices=[('Farmácia municipal', 'Farmácia municipal'), ('Compra', 'Compra'), ('Farmácia municipal e compra', 'Farmácia municipal e compra'), ('Outros', 'Outros')], max_length=30, verbose_name='Origem da medicação'),
        ),
        migrations.AlterField(
            model_name='record',
            name='natural_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_cards.City', verbose_name='Naturalidade'),
        ),
        migrations.AlterField(
            model_name='record',
            name='old_people_in_family',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='Idosos na família'),
        ),
        migrations.AlterField(
            model_name='record',
            name='pregnant_or_lactating',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='Gestante ou lactante'),
        ),
        migrations.AlterField(
            model_name='record',
            name='race',
            field=models.CharField(choices=[('Branca', 'Branca'), ('Preta', 'Preta'), ('Parda', 'Parda'), ('Amarela', 'Amarela'), ('Indígena', 'Indígena')], default='Não declarada', max_length=20, verbose_name='Cor ou raça'),
        ),
        migrations.AlterField(
            model_name='record',
            name='scholarity',
            field=models.CharField(choices=[('Ensino Fundamental incompleto', 'Ensino Fundamental incompleto'), ('Ensino Fundamental em andamento', 'Ensino Fundamental em andamento'), ('Ensino Fundamental completo', 'Ensino Fundamental completo'), ('Ensino Médio incompleto', 'Ensino Médio incompleto'), ('Ensino Médio em andamento', 'Ensino Médio em andamento'), ('Ensino Médio completo', 'Ensino Médio completo'), ('Ensino Superior incompleto', 'Ensino Superior incompleto'), ('Ensino Superior em andamento', 'Ensino Superior em andamento'), ('Ensino Superior completo', 'Ensino Superior completo')], max_length=30, verbose_name='Escolaridade'),
        ),
        migrations.AlterField(
            model_name='record',
            name='source_of_income',
            field=models.CharField(choices=[('Informal apenas', 'Informal apenas'), ('Formal apenas', 'Formal apenas'), ('Ambas', 'Ambas')], max_length=30, verbose_name='Fonte da renda'),
        ),
        migrations.AlterField(
            model_name='record',
            name='treatment',
            field=models.CharField(choices=[('Até um ano', 'Até um ano'), ('Um a dois anos', 'Um a dois anos'), ('Dois a três anos', 'Dois a três anos'), ('Mais de três anos', 'Mais de três anos')], max_length=30, verbose_name='Tempo de tratamento'),
        ),
    ]
