# Generated by Django 3.0.7 on 2020-06-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='agreement',
            field=models.CharField(max_length=3, verbose_name='Possui convênio'),
        ),
        migrations.AlterField(
            model_name='record',
            name='alcohol_or_drug_user',
            field=models.CharField(max_length=3, verbose_name='Usuário de álcool ou drogas'),
        ),
        migrations.AlterField(
            model_name='record',
            name='debts',
            field=models.CharField(max_length=3, verbose_name='Dídivas'),
        ),
        migrations.AlterField(
            model_name='record',
            name='disabled_in_family',
            field=models.CharField(max_length=3, verbose_name='Deficientes na família'),
        ),
        migrations.AlterField(
            model_name='record',
            name='early_pregnancy',
            field=models.CharField(max_length=3, verbose_name='Gravidez precoce'),
        ),
        migrations.AlterField(
            model_name='record',
            name='estimated_income',
            field=models.CharField(max_length=32, verbose_name='Renda estimada'),
        ),
        migrations.AlterField(
            model_name='record',
            name='gender',
            field=models.CharField(max_length=20, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='record',
            name='health_problems_in_family',
            field=models.CharField(max_length=30, verbose_name='Doenças na família'),
        ),
        migrations.AlterField(
            model_name='record',
            name='housing_condition',
            field=models.CharField(max_length=30, verbose_name='Condição de moradia'),
        ),
        migrations.AlterField(
            model_name='record',
            name='medication_origin',
            field=models.CharField(max_length=30, verbose_name='Origem da medicação'),
        ),
        migrations.AlterField(
            model_name='record',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome usuário'),
        ),
        migrations.AlterField(
            model_name='record',
            name='old_people_in_family',
            field=models.CharField(max_length=3, verbose_name='Idosos na família'),
        ),
        migrations.AlterField(
            model_name='record',
            name='pregnant_or_lactating',
            field=models.CharField(max_length=3, verbose_name='Gestante ou lactante'),
        ),
        migrations.AlterField(
            model_name='record',
            name='race',
            field=models.CharField(max_length=20, verbose_name='Raça'),
        ),
        migrations.AlterField(
            model_name='record',
            name='scholarity',
            field=models.CharField(max_length=30, verbose_name='Escolaridade'),
        ),
        migrations.AlterField(
            model_name='record',
            name='source_of_income',
            field=models.CharField(max_length=30, verbose_name='Fonte da renda'),
        ),
        migrations.AlterField(
            model_name='record',
            name='treatment',
            field=models.CharField(max_length=30, verbose_name='Tempo de tratamento'),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Race',
        ),
        migrations.DeleteModel(
            name='Scolarity',
        ),
    ]
