# Generated by Django 2.2.7 on 2019-11-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_cards', '0002_auto_20191128_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='age',
        ),
        migrations.AlterField(
            model_name='record',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome usuárix'),
        ),
    ]
