# Generated by Django 2.2.7 on 2019-11-28 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_cards', '0003_auto_20191128_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='has_benefits',
        ),
    ]
