# Generated by Django 2.2.7 on 2019-11-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_cards', '0004_remove_record_has_benefits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialbenefit',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
    ]
